name: Release
on:
  push:
    tags: v*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: "npm"
          registry-url: 'https://registry.npmjs.org'
          scope: '@brightdata'
      - run: npm ci
      - run: npm audit signatures
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
